feed/urls.py
from django.urls import path
from . import views


app_name = 'feed'

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("detail/<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

til/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path
from feed import urls as feed_url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include( feed_url, namespace='feed')), 
    url('', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Post(models.Model):
    text = models.CharField(max_length=140)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.text[0:100]
    

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        User, 
        on_delete=models.CASCADE,
        related_name="profile"
        
    )
    image = ImageField(upload_to='profiles')

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """ Create a new Profile() object when a Django User is create."""
    if created:
        Profile.objects.create(user=instance)    

feed/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

from .models import Post

# Create your views here.


class HomePage(ListView):
    http_method_names = ['get']
    template_name = 'feed/homepage.html'
    model = Post
    context_object_name = 'posts'  # object
    queryset = Post.objects.all().order_by('-id')[0:30]


class PostDetailView(DetailView):
    http_method_names = ['get']
    template_name = 'feed/detail.html'
    model = Post
    context_object_name = "post"


class CreateNewPost(LoginRequiredMixin, CreateView):
    template_name = 'feed/create.html'
    fields = ['text']
    model = Post
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        post = Post.objects.create(
            text=request.POST.get('text'),
            author=request.user
        )
        return render(
            request,
            "includes/post.html",
            {
                "post": post,
                "show_detail_link": True,
            },
            content_type="application/html"
        )

profiles/views.py
from django.shortcuts import render

# Create your views here.

feed/templates/feed/create.html
{% extends 'base.html' %}

{% block title %}Create a new post{% endblock title %}

{% block body %}
    <form method="POST" action=".">

    {% csrf_token %}
    {{form.as_p}}
    <div>
        <div class="my-3">
            <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type ="submit">
            <span class="mr-2">Create Post</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
            </svg>
            </button>
        </div>
    </div>
    
    </form>
{% endblock body %}

feed/templates/feed/detail.html
{% extends 'base.html' %}

{% block title %}{{post.text}} by {{post.author.username}}{% endblock  %}

{% block body %}
    <!-- component -->
    {% include "includes/post.html" with post=post %}
        
{% endblock body %}

feed/templates/feed/homepage.html
{% extends 'base.html' %}

{% block title %} Homepage {% endblock  %}

{% block body %}
    <div id="posts-container">
        {% for post in posts %}
        <!-- component -->
        {% include "includes/post.html" with post=post  show_detail_link=True %}
        {% endfor %}
    </div>
{% endblock  %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
    <title>{% block title %}Default Page{% endblock  %}</title>
</head>
<body>
    <!-- component -->

    <div class="min-h-screen flex flex-row bg-gray-100">
        <div class="flex flex-col w-56 bg-white rounded-r-3xl overflow-hidden">
              <div class="flex items-center justify-center h-20 shadow-md">
                <h1 class="text-3xl uppercase text-indigo-500">TIL</h1>
              </div>
              <ul class="flex flex-col py-4">
                <li>
                    <a href="/" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                    <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-home"></i></span>
                    <span class="text-sm font-medium">Home</span>
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url 'feed:new_post' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800 js-toggle-modal">
                    <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-layer-plus"></i></span>
                    <span class="text-sm font-medium">New post</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'account_logout' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                    <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-out"></i></span>
                    <span class="text-sm font-medium">Logout</span>
                    </a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'account_login' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                    <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-in"></i></span>
                    <span class="text-sm font-medium">Login</span>
                    </a>
                </li>
                {% endif %}
              </ul>
          </div>
          <div class="p-16">
              {% block body %}
                  {% block content %}{% endblock  %}

              {% endblock  %}
              </div>
      <!-- component -->
      {% if request.user.is_authenticated %}
      <div class="flex items-center justify-center fixed left-0 bottom-0 w-full h-full bg-gray-800 bg-opacity-90 hidden js-modal">
        <div class="bg-white rounded-lg w-1/2">
          <div class="flex flex-col items-start p-4">
            <div class="flex items-center w-full">
              <div class="text-gray-900 font-medium text-lg">New Post</div>
          <svg class="ml-auto fill-current text-gray-700 w-6 h-6 cursor-pointer js-toggle-modal" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
            <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"/>
            </svg>
            </div>
            <hr>
            <div class="w-full">
              {# TODO: Add the ajax form#}
              <textarea class="border-2 border-blue-500 my-4  w-full js-post-text" rows="3" maxlength="140" placeholder="Enter your post"  data-post-url="{% url 'feed:new_post'%}"></textarea>
            </div>
            <hr>
            <div class="ml-auto">
              <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-1 px-3 inline-flex items-center text-sm mt-4 js-submit" type ="button">
                  <span class="mr-2">Create Post</span>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                      <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                  </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js'%}"></script>
</body>
</html>

templates/includes/post.html
 {% load thumbnail %}
 
     <div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style='width: 50rem'>
            <div class="flex justify-between items-center">
                <span class="font-light text-gray-600">{{post.date|date:"F j, Y, g:i:a"}}</span>
                {% comment %} <a class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500" href="#">Design</a> {% endcomment %}
            </div>
            <div class="mt-2">
                <p class="mt-2 text-gray-600">{{post.text}}</p>
            </div>
            <div class="flex justify-between items-center mt-4">
                {% if show_detail_link %}
                <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id%}">
                {# TODO Add a detail url #}
                    Read more
                </a>
                {% else %}
                    <span>&nbsp;</span>
                {% endif %}
                <div>
                {# TODO: User needs a link to their bio and a photo and a  thumbnail and a name #}
                    <a class="flex items-center" href="#">
                    {% thumbnail post.author.profile.image "373x373" crop="center" as im %}
                        <img src="{{ im.url }}" class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block"  alt="avatar">
                    {% endthumbnail %}
                        <h1 class="text-gray-700 font-bold">{{post.author.username}}</h1>
                    </a>
                </div>
            </div>
        </div>